# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0008_auto_20161017_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testflow', models.CharField(default='6666', max_length=50, verbose_name='\u6d4b\u8bd5')),
                ('state', river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
            ],
        ),
    ]
