# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='menu',
            new_name='menu_item',
        ),
    ]
