# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:01
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mymodel',
            managers=[
                ('mnage', django.db.models.manager.Manager()),
            ],
        ),
    ]
