# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0008_auto_20161017_0916'),
        ('mysite', '0002_auto_20161101_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='somework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u9898\u76ee')),
                ('content', models.TextField(verbose_name='\u6c47\u62a5')),
                ('state', river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name='\u63d0\u4ea4\u72b6\u6001')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mymodel',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='state',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State', verbose_name='\u72b6\u6001'),
        ),
    ]
