# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20161117_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='mysite.MenuItem', verbose_name='\u83dc\u5355'),
        ),
    ]
