# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20161112_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='menugroup',
            field=models.OneToOneField(help_text='\u83dc\u5355', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menugroup', to='mysite.MenuGroup'),
        ),
    ]
