# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='state',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='river.State', verbose_name='\u72b6\u6001'),
        ),
    ]
