# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20161105_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
