# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20161112_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='menugroup',
            field=models.ForeignKey(help_text='\u83dc\u5355', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menugroup', to='mysite.MenuGroup'),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='mysite.menu_item', verbose_name='\u83dc\u5355'),
        ),
    ]
