# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56fe\u6807')),
                ('uil', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.menu_item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
