# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20161109_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='menu_item',
            field=models.ForeignKey(help_text='\u83dc\u5355', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.menu_item'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(help_text='\u8f93\u5165\u7535\u8bdd\u53f7\u7801', max_length=16, verbose_name='\u7535\u8bdd'),
        ),
    ]
