# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20161109_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u83dc\u5355\u5206\u7ec4', max_length=16, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='menu_item',
            field=models.ForeignKey(help_text='\u83dc\u5355', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.menu_item'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='MenuGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menugroup', to='mysite.MenuGroup', verbose_name='\u83dc\u5355\u7ec4'),
        ),
    ]
