# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_menugroup_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(help_text='\u8f93\u5165\u7535\u8bdd\u53f7\u7801', max_length=16, null=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
