# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20161111_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='menu_item',
            field=models.OneToOneField(help_text='\u83dc\u5355', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='mysite.MenuGroup'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='mysite.menu_item', verbose_name='\u7236\u8282\u70b9'),
        ),
    ]
