# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20161111_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='MenuGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menugroup', to='mysite.MenuGroup', verbose_name='\u83dc\u5355\u7ec4'),
        ),
    ]
